version: 2

# common job parameters as a template
defaults: &defaults
  working_directory: ~/app
  docker:
    # the Docker image with Cypress preinstalled
    - image: cypress/internal:cy-0.19.2

jobs:
  build:
    <<: *defaults
    steps:
      - checkout

  e2e:
    # <<: *defaults
    steps:
      - run:
          name: Running E2E tests
          command: cypress run --reporter junit --reporter-options "mochaFile=results/my-test-output.xml"
      - store_test_results:
          path: results
      - store_artifacts:
          path: cypress/videos
      - store_artifacts:
          path: cypress/screenshots

workflows:
  version: 2
  "lint and test":
    jobs:
      - build
      - e2e:
        requires:
        - build
